# Generated by Django 6.0.6 on 2026-07-03 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("secao", "0002_secao_imagem_nuvem"),
    ]

    operations = [
        migrations.RenameField(
            model_name="secao",
            old_name="texto_resposta",
            new_name="resumo",
        ),
    ]
