# Generated by Django 6.0.6 on 2026-07-04 15:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("secao", "0003_rename_texto_resposta_secao_resumo"),
    ]

    operations = [
        migrations.AddField(
            model_name="secao",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
