# Generated by Django 6.0.6 on 2026-07-05 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("secao", "0004_secao_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="secao",
            name="resumo",
            field=models.TextField(blank=True, null=True),
        ),
    ]
