# Generated by Django 6.0.6 on 2026-07-06 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("secao", "0005_alter_secao_resumo"),
    ]

    operations = [
        migrations.AddField(
            model_name="secao",
            name="status",
            field=models.CharField(
                choices=[
                    ("processando", "Processando"),
                    ("concluido", "Concluído"),
                    ("erro", "Erro"),
                ],
                default="processando",
                max_length=20,
            ),
        ),
    ]
